-- MySQL Script generated by MySQL Workbench
-- Sun May 17 11:23:36 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema repositorio_academico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema repositorio_academico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `repositorio_academico` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `repositorio_academico` ;

-- -----------------------------------------------------
-- Table `repositorio_academico`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`promocion` (
  `id_promocion` INT NOT NULL AUTO_INCREMENT,
  `anio` INT NOT NULL COMMENT 'Año de la promoción (ej: 2023)',
  `descripcion` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Descripción opcional de la promoción',
  PRIMARY KEY (`id_promocion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `anio` ON `repositorio_academico`.`promocion` (`anio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre de la categoría (ej: Tecnología, Salud)',
  `descripcion` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Descripción breve de la categoría',
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `nombre` ON `repositorio_academico`.`categoria` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del rol',
  `nombre` VARCHAR(50) NOT NULL COMMENT 'Nombre del rol (ej: Director, Subdirector, Profesor)',
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Tabla de roles del sistema';

CREATE UNIQUE INDEX `nombre` ON `repositorio_academico`.`rol` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del usuario',
  `id_rol` INT NOT NULL COMMENT 'ID del rol asignado al usuario',
  `nombre_completo` VARCHAR(150) NOT NULL COMMENT 'Nombre completo de la directora',
  `email` VARCHAR(200) NOT NULL COMMENT 'Correo institucional de la directora',
  `contrasena_hash` VARCHAR(255) NOT NULL COMMENT 'Contraseña hasheada con bcrypt',
  `creado_en` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de creación del usuario',
  `ultimo_acceso` DATETIME NULL DEFAULT NULL COMMENT 'Última vez que inició sesión',
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `repositorio_academico`.`rol` (`id_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Tabla de usuarios del sistema (solo Dirección)';

CREATE UNIQUE INDEX `email` ON `repositorio_academico`.`usuario` (`email` ASC) VISIBLE;

CREATE INDEX `id_rol` ON `repositorio_academico`.`usuario` (`id_rol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`proyecto` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(300) NOT NULL COMMENT 'Título completo del proyecto de investigación',
  `descripcion_breve` TEXT NULL DEFAULT NULL COMMENT 'Resumen breve del proyecto',
  `tema` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Tema específico del proyecto',
  `id_promocion` INT NOT NULL COMMENT 'Año de promoción al que pertenece el proyecto',
  `id_categoria` INT NOT NULL COMMENT 'Categoría temática del proyecto',
  `registrado_por` INT NOT NULL COMMENT 'Usuario (directora) que registró el proyecto',
  `creado_en` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de registro del proyecto en el sistema',
  PRIMARY KEY (`id_proyecto`),
  CONSTRAINT `proyecto_ibfk_1`
    FOREIGN KEY (`id_promocion`)
    REFERENCES `repositorio_academico`.`promocion` (`id_promocion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proyecto_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `repositorio_academico`.`categoria` (`id_categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proyecto_ibfk_3`
    FOREIGN KEY (`registrado_por`)
    REFERENCES `repositorio_academico`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `id_promocion` ON `repositorio_academico`.`proyecto` (`id_promocion` ASC) VISIBLE;

CREATE INDEX `id_categoria` ON `repositorio_academico`.`proyecto` (`id_categoria` ASC) VISIBLE;

CREATE INDEX `registrado_por` ON `repositorio_academico`.`proyecto` (`registrado_por` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`archivo_pdf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`archivo_pdf` (
  `id_archivo` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT NOT NULL COMMENT 'Proyecto al que pertenece este archivo',
  `nombre_archivo` VARCHAR(255) NOT NULL COMMENT 'Nombre original del archivo PDF subido',
  `ruta_almacenamiento` VARCHAR(500) NOT NULL COMMENT 'Ruta relativa en el servidor donde se guardó el PDF',
  `tamano_bytes` BIGINT NULL DEFAULT NULL COMMENT 'Tamaño del archivo en bytes',
  `subido_en` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de subida del archivo',
  PRIMARY KEY (`id_archivo`),
  CONSTRAINT `archivo_pdf_ibfk_1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `repositorio_academico`.`proyecto` (`id_proyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `id_proyecto` ON `repositorio_academico`.`archivo_pdf` (`id_proyecto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`envio` (
  `id_envio` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT NOT NULL COMMENT 'Proyecto cuyo PDF fue enviado',
  `id_usuario` INT NOT NULL COMMENT 'Usuario (directora) que realizó el envío',
  `enviado_en` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y hora en que se envió el correo',
  `motivo` VARCHAR(300) NULL DEFAULT NULL COMMENT 'Motivo o nota del envío (ej: solicitado por docente)',
  PRIMARY KEY (`id_envio`),
  CONSTRAINT `envio_ibfk_1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `repositorio_academico`.`proyecto` (`id_proyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `envio_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `repositorio_academico`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `id_proyecto` ON `repositorio_academico`.`envio` (`id_proyecto` ASC) VISIBLE;

CREATE INDEX `id_usuario` ON `repositorio_academico`.`envio` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`destinatario_envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`destinatario_envio` (
  `id_destinatario` INT NOT NULL AUTO_INCREMENT,
  `id_envio` INT NOT NULL COMMENT 'ID del envío principal',
  `email` VARCHAR(200) NOT NULL COMMENT 'Correo electrónico del destinatario',
  `nombre` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Nombre del destinatario',
  PRIMARY KEY (`id_destinatario`),
  CONSTRAINT `destinatario_envio_ibfk_1`
    FOREIGN KEY (`id_envio`)
    REFERENCES `repositorio_academico`.`envio` (`id_envio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `id_envio` ON `repositorio_academico`.`destinatario_envio` (`id_envio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(150) NOT NULL COMMENT 'Nombre completo del estudiante',
  `anio_egreso` INT NULL DEFAULT NULL COMMENT 'Año en el que egresó el estudiante',
  PRIMARY KEY (`id_estudiante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositorio_academico`.`proyecto_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositorio_academico`.`proyecto_estudiante` (
  `id_proyecto` INT NOT NULL,
  `id_estudiante` INT NOT NULL,
  PRIMARY KEY (`id_proyecto`, `id_estudiante`),
  CONSTRAINT `proyecto_estudiante_ibfk_1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `repositorio_academico`.`proyecto` (`id_proyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proyecto_estudiante_ibfk_2`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `repositorio_academico`.`estudiante` (`id_estudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Relación N:M — un proyecto puede tener múltiples estudiantes';

CREATE UNIQUE INDEX `proyecto_estudiante_id_estudiante_id_proyecto_unique` ON `repositorio_academico`.`proyecto_estudiante` (`id_proyecto` ASC, `id_estudiante` ASC) VISIBLE;

CREATE INDEX `id_estudiante` ON `repositorio_academico`.`proyecto_estudiante` (`id_estudiante` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
